# This script deploys your website automatically
name: gh-pages deployment

# Only trigger this script when you push to the gh-pages branch
on:
  push:
    branches: [ master ]

# Specify the tasks to run when this script gets triggered
jobs:
  build:
    runs-on: ubuntu-latest

    # Download branch
    steps:
    - uses: actions/checkout@v2
    
    - name: Install and Build
      run: |
        npm install
        npm run build
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: public
